### ISSUE TITLE
docker image tagging scheme?

### ISSUE THREAD

**Issue by eckdanny-osi** [ca-cwds/dashboard#22]
There has been confusion regarding versioning of the docker hub tag. The root cause being the tags being published on hub are not immutable (e.g.; `0.5.8.` is being overwritten again and again, and its not possible to easily trace deployment artifacts to git hashes.)

**Comment by ratneshraval** [comment]
We need CI setup for dashboard project. Tag is currently hardcoded :(

**Comment by eckdanny-osi** [comment]
Docker's tagging scheme is not prescriptive (e.g.; semver) but we _should_ be publishing immutable images. How about tagging images with git refspecs instead? If/when `dashboard` stabilizes, pegging to _releases_ is probably best.
